=== Archov/RomCurator/seed-data/Moby/MobyGames.Schema.Json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "MobyGames Catalog Schema",
  "description": "A schema to validate the MobyGames JSON catalog format.",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "developers": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "genres": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "id": {
        "type": "integer"
      },
      "moby_score": {
        "type": ["number", "null"]
      },
      "moby_url": {
        "type": "string",
        "format": "uri"
      },
      "platforms": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "publishers": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "release_date": {
        "type": "string"
      },
      "title": {
        "type": "string"
      }
    },
    "required": [
      "developers",
      "genres",
      "id",
      "moby_score",
      "moby_url",
      "platforms",
      "publishers",
      "release_date",
      "title"
    ]
  }
}

=== Archov/RomCurator/seed-data/Moby/Computer/MobyGames-DOS-2001+-Catalog.json
[{"developers":[],"genres":["Racing / Driving","Tank","3rd-person (Other)"],"id":54227,"moby_score":null,"moby_url":"https://www.mobygames.com/game/54227/3d-cargame/","platforms":["DOS"],"publishers":[],"release_date":"2001","title":"3D Cargame"},{"developers":[],"genres":["Adventure","1st-person","Interactive fiction / text adventure"],"id":28964,"moby_score":null,"moby_url":"https://www.mobygames.com/game/28964/adventure-book-included-games/","platforms":["DOS"],"publishers":[],"release_date":"2001","title":"Adventure Book (included games)"},{"developers":[],"genres":["Adventure","Interactive fiction / text adventure","Puzzle elements","Fantasy","Text-based / Spreadsheet","Text parser"],"id":135396,"moby_score":null,"moby_url":"https://www.mobygames.com/game/135396/adventure-ii/","platforms":["DOS","Mainframe","Linux"],"publishers":[],"release_date":"1978","title":"Adventure II"},{"developers":[],"genres":["Compilation"],"id":75997,"moby_score":null,"moby_url":"https://www.mobygames.com/game/75997/amiga-classics/","platforms":["Linux","DOS","Windows","Amiga","Macintosh"],"publishers":["Epic Marketing Ltd.","Oxygen Interactive"],"release_date":"2001","title":"Amiga Classics"},{"developers":[],"genres":["Compilation"],"id":226311,"moby_score":null,"moby_url":"https://www.mobygames.com/game/226311/amiga-classix/","platforms":["Amiga","DOS","Windows","Linux","Macintosh"],"publishers":["Epic Marketing Ltd."],"release_date":"2001","title":"Amiga ClassiX"},{"developers":[],"genres":["Action","Sci-fi / futuristic","Top-down","Shooter","2D scrolling","Space flight","Direct control"],"id":235453,"moby_score":null,"moby_url":"https://www.mobygames.com/game/235453/battle-insects/","platforms":["DOS"],"publishers":["5 Union Software Group SL"],"release_date":"2001","title":"Battle Insects"},{"developers":[],"genres":["Top-down","Puzzle","Fixed / flip-screen","Direct control"],"id":203423,"moby_score":null,"moby_url":"https://www.mobygames.com/game/203423/bips/","platforms":["DOS"],"publishers":[],"release_date":"2001","title":"Bips"},{"developers":[],"genres":["Compilation"],"id":13557,"moby_score":null,"moby_url":"https://www.mobygames.com/game/13557/descent-venture-pack/","platforms":["DOS","Windows"],"publishers":["Interplay Entertainment Corp."],"release_date":"2001","title":"Descent: Venture Pack"},{"developers":[],"genres":["Compilation"],"id":59641,"moby_score":null,"moby_url":"https://www.mobygames.com/game/59641/dungeon-keeper-dungeon-keeper-2/","platforms":["Windows","DOS"],"publishers":["Electronic Arts, Inc."],"release_date":"2001","title":"Dungeon Keeper + Dungeon Keeper 2"},{"developers":[],"genres":["Compilation"],"id":21121,"moby_score":null,"moby_url":"https://www.mobygames.com/game/21121/football-masters-championship-rugby-manager/","platforms":["DOS","Windows"],"publishers":["Midas Interactive Entertainment Ltd."],"release_date":"2001","title":"Football Masters + Championship Rugby Manager"},{"developers":[],"genres":["Compilation"],"id":13560,"moby_score":null,"moby_url":"https://www.mobygames.com/game/13560/game-hits-1/","platforms":["DOS","Windows"],"publishers":["JoWooD Productions Software AG"],"release_date":"2001","title":"Game-Hits 1"},{"developers":[],"genres":["Compilation"],"id":5554,"moby_score":null,"moby_url":"https://www.mobygames.com/game/5554/gamefest-forgotten-realms-classics/","platforms":["DOS","Windows"],"publishers":["Interplay Entertainment Corp."],"release_date":"2001","title":"Gamefest: Forgotten Realms Classics"},{"developers":[],"genres":["Action","Platform","Fangame"],"id":6474,"moby_score":null,"moby_url":"https://www.mobygames.com/game/6474/jet-set-willy-ii-the-final-frontier/","platforms":["DOS"],"publishers":[],"release_date":"2001","title":"Jet Set Willy II: The Final Frontier"},{"developers":[],"genres":["Adventure","Sci-fi / futuristic","Interactive fiction / text adventure"],"id":28985,"moby_score":null,"moby_url":"https://www.mobygames.com/game/28985/kingdom-without-end/","platforms":["DOS","Browser"],"publishers":[],"release_date":"2001","title":"Kingdom Without End"},{"developers":[],"genres":["Adventure","Side view","Puzzle elements","Detective / mystery","Comedy","Graphic adventure","Point and select"],"id":11706,"moby_score":null,"moby_url":"https://www.mobygames.com/game/11706/larry-vales-ii-dead-girls-are-easy/","platforms":["DOS"],"publishers":[],"release_date":"2001","title":"Larry Vales II: Dead Girls are Easy"},{"developers":[],"genres":["Compilation"],"id":25015,"moby_score":null,"moby_url":"https://www.mobygames.com/game/25015/max-max-2/","platforms":["Windows","DOS"],"publishers":["Virgin Interactive Entertainment (Europe) Ltd.","Interplay Entertainment Corp."],"release_date":"2001","title":"M.A.X. & M.A.X. 2"},{"developers":[],"genres":["Action","Side view","Platform","2D scrolling","Fangame"],"id":61674,"moby_score":null,"moby_url":"https://www.mobygames.com/game/61674/mario-luigi/","platforms":["DOS"],"publishers":["Wiering Software"],"release_date":"2001","title":"Mario & Luigi"},{"developers":["Hammer Technologies"],"genres":["Action","Arcade","Side view","Paddle / Pong","Fixed / flip-screen"],"id":166152,"moby_score":null,"moby_url":"https://www.mobygames.com/game/166152/noid/","platforms":["DOS"],"publishers":["FastTrak Software Publishing Ltd."],"release_date":"2001","title":"Noid"},{"developers":[],"genres":["Compilation"],"id":137578,"moby_score":null,"moby_url":"https://www.mobygames.com/game/137578/pc-games-collection-2/","platforms":["DOS","Windows"],"publishers":["Computec Media AG"],"release_date":"2001","title":"PC Games Collection 2"},{"developers":[],"genres":["Adventure","Puzzle elements","Comedy","3rd-person (Other)","Graphic adventure","Point and select"],"id":119966,"moby_score":6.96,"moby_url":"https://www.mobygames.com/game/119966/permanent-daylight/","platforms":["DOS"],"publishers":[],"release_date":"2001","title":"Permanent Daylight"},{"developers":["GASPOP Software"],"genres":["Adventure","Puzzle elements","Detective / mystery","3rd-person (Other)","Graphic adventure"],"id":6347,"moby_score":7.57,"moby_url":"https://www.mobygames.com/game/6347/pleurghburg-dark-ages/","platforms":["DOS","Windows"],"publishers":["GASPOP Software"],"release_date":"2001","title":"Pleurghburg: Dark Ages"},{"developers":[],"genres":["Adventure","Side view","Puzzle elements","Comedy","Graphic adventure","Point and select"],"id":72442,"moby_score":null,"moby_url":"https://www.mobygames.com/game/72442/richard-longhurst-and-the-box-that-ate-time/","platforms":["DOS","Windows"],"publishers":[],"release_date":"2001","title":"Richard Longhurst and the Box that Ate Time"},{"developers":["Burning Dreams"],"genres":["Adventure","1st-person","Puzzle elements"],"id":61192,"moby_score":null,"moby_url":"https://www.mobygames.com/game/61192/shadow-ape/","platforms":["DOS","Atari ST"],"publishers":["Burning Dreams"],"release_date":"1992","title":"Shadow Ape"},{"developers":[],"genres":["Compilation"],"id":60292,"moby_score":null,"moby_url":"https://www.mobygames.com/game/60292/speccy-classix-3000/","platforms":["Linux","DOS","Windows","Amiga","Atari ST","ZX Spectrum","Macintosh","Acorn 32-bit"],"publishers":["Epic Marketing Ltd.","Epicdirect"],"release_date":"1999","title":"Speccy Classix 3000"},{"developers":["Hammer Technologies"],"genres":["Racing / Driving","Arcade","Behind view","Direct control","Automobile","Track racing"],"id":167531,"moby_score":null,"moby_url":"https://www.mobygames.com/game/167531/speed-4-dummies/","platforms":["DOS"],"publishers":["FastTrak Software Publishing Ltd."],"release_date":"2001","title":"Speed 4 Dummies"},{"developers":["SimTex, Inc."],"genres":["Strategy / tactics","Sci-fi / futuristic","Top-down","Managerial / business simulation","4X"],"id":4244,"moby_score":null,"moby_url":"https://www.mobygames.com/game/4244/star-lords/","platforms":["DOS"],"publishers":["Quicksilver Software, Inc."],"release_date":"2001","title":"Star Lords"},{"developers":["Hammer Technologies"],"genres":["Action","Arcade","Side view","Platform","Fantasy","2D scrolling"],"id":40043,"moby_score":null,"moby_url":"https://www.mobygames.com/game/40043/the-castle-of-dr-malvado/","platforms":["DOS"],"publishers":["The Gamehouse Team"],"release_date":"2001","title":"The Castle of Dr. Malvado"},{"developers":[],"genres":["1st-person","Role-playing (RPG)","Fantasy","Turn-based"],"id":175495,"moby_score":null,"moby_url":"https://www.mobygames.com/game/175495/tower-of-fortune/","platforms":["DOS"],"publishers":[],"release_date":"2001","title":"Tower of Fortune"},{"developers":["Artsoft Entertainment"],"genres":["Action","Sci-fi / futuristic","Top-down","Fantasy","Puzzle","Diagonal-down","Fixed / flip-screen","Point and select"],"id":191814,"moby_score":null,"moby_url":"https://www.mobygames.com/game/191814/mirror-magic/","platforms":["Linux","Macintosh","Windows","DOS","Android"],"publishers":["Artsoft Entertainment"],"release_date":"1995-05-03","title":"Mirror Magic"},{"developers":["MDickie Limited"],"genres":["Action","Side view","2D scrolling","Direct control"],"id":239349,"moby_score":null,"moby_url":"https://www.mobygames.com/game/239349/big-bumps/","platforms":["DOS"],"publishers":["MDickie Limited"],"release_date":"2001-02","title":"Big Bumps"},{"developers":[],"genres":["Adventure","Sci-fi / futuristic","Side view","Comedy","Fixed / flip-screen","Graphic adventure","Text parser","Fangame"],"id":54958,"moby_score":null,"moby_url":"https://www.mobygames.com/game/54958/space-quest-the-lost-chapter/","platforms":["DOS"],"publishers":[],"release_date":"2001-02","title":"Space Quest: The Lost Chapter"},{"developers":["Outhouse Software"],"genres":["Action","Arcade","Side view","Platform","2D scrolling"],"id":172903,"moby_score":null,"moby_url":"https://www.mobygames.com/game/172903/super-roco-bros/","platforms":["DOS"],"publishers":["Outhouse Software"],"release_date":"2001-02","title":"Super Roco Bros."},{"developers":["Ingenieurb\u00fcro FRANKE"],"genres":[
